version: "3.8"

services:
  postgres:
    container_name: iarvs_pgdb
    image: postgres:16
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iarvs

    ports:
      - "5432:5432"

    networks:
      - mynetwork

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: iarvs_pgadmin
    image: dpage/pgadmin4:8.12
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "8080:80"

    networks:
      - mynetwork

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
  container_name: iarvs_redis
  image: redis:latest
  restart: always
  ports:
    - "6379:6379"
  networks:
    - mynetwork
  volumes:
    - redis_data:/data

volumes:
  postgres_data:
    driver: local

  pgadmin_data:
    driver: local

  redis_data:

networks:
  mynetwork:
    driver: bridge
